version: "3.9"

services:

  backend:
    build: ./backend
    container_name: magictap-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - magictap-network

  mongodb:
    image: mongo:7
    container_name: magictap-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - magictap-network

volumes:
  mongo-data:

networks:
  magictap-network:
    driver: bridge